language: csharp  
dist: trusty  
env:  
  - CLI_VERSION=latest
dotnet: 2.0.0
mono:  
  - latest
os:  
  - linux
branches:  
  only:
    - master
before-install:
  - sudo apt-get -qq update
  - sudo apt-get install -y --no-install-recommends unzip git libc6 libc6-dev libc6-dbg
install: 
  - chmod +x ./install-mono.sh
  - ./install-mono.sh
script:  
  - chmod +x ./ci-script.sh
  - ./ci-script.sh
