language: csharp  
sudo: required  
dist: trusty  
sudo: false
env:  
  - CLI_VERSION=latest
dotnet: 2.0.0
mono:  
  - latest
os:  
  - linux
branches:  
  only:
    - master
install: 
  - chmod +x ./install-mono.sh
  - ./install-mono.sh
script:  
  - chmod +x ./ci-script.sh
  - ./ci-script.sh
